### ISSUE TITLE
Ordering for ledger.list is incorrect

### ISSUE THREAD

**Issue by tantommy** [the-lifted-initiative/many-framework#53]
Ran this command to get list of transactions but ordering is off:
`many message --server http://localhost:8000 ledger.list '{1:2}'`

**Comment by hansl** [comment]
The problem is the key is sorted by byte values, but transaction IDs can grow larger over time. So if you have more than 256 transactions (in non-blockchain) the transaction ID is going to grow and the list is going to be out of order.

**Comment by hansl** [comment]
The key right now is `/transactions/<Tx_ID>/...` and if `Tx_ID` is different sizes then that messes up the order. One easy solution is to force Tx_ID to be a u64.
