### ISSUE TITLE
many-abci also needs the allow-origin flag

### ISSUE THREAD

**Issue by hansl** [the-lifted-initiative/many-framework#91]
Otherwise, it won't accept WebAuthn requests. It does validate the signature before putting the requests in the mempool, so this is necessary.

cc @tantommy

**Comment by fmorency** [comment]
There is an issue but it's not the one you think it is.

The issue is caused by the `thread_local!` global variable being used in an async context (ABCI) which causes the global variable to be uninitialized in the thread.
